[package]
name = "airgap"
version = "0.1.5"
edition = "2024"
authors = ["Sven Sauleau <sven@sauleau.com>"]
description = "Security for the modern age of AI: defend against bad AI agents and malicious npm packages"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xtuc/airgap"

[dependencies]
fuser = "0.17"
nix = { version = "0.31", features = ["mount", "sched", "process", "signal", "fs", "uio", "dir", "user"] }
dotenvy = "0.15"
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
